#ifndef IMAGEIO_CGIMAGEPROPS
#define IMAGEIO_CGIMAGEPROPS

// https://developer.apple.com/library/mac/documentation/GraphicsImaging/Reference/CGImageProperties_Reference/

extern const CFStringRef kCGImagePropertyTIFFDictionary;
extern const CFStringRef kCGImagePropertyGIFDictionary;
extern const CFStringRef kCGImagePropertyJFIFDictionary;
extern const CFStringRef kCGImagePropertyExifDictionary;
extern const CFStringRef kCGImagePropertyPNGDictionary;
extern const CFStringRef kCGImagePropertyIPTCDictionary;
extern const CFStringRef kCGImagePropertyGPSDictionary;
extern const CFStringRef kCGImagePropertyRawDictionary;
extern const CFStringRef kCGImagePropertyCIFFDictionary;
extern const CFStringRef kCGImageProperty8BIMDictionary;
extern const CFStringRef kCGImagePropertyDNGDictionary;
extern const CFStringRef kCGImagePropertyExifAuxDictionary;

extern const CFStringRef kCGImagePropertyGIFLoopCount;
extern const CFStringRef kCGImagePropertyGIFDelayTime;
extern const CFStringRef kCGImagePropertyGIFImageColorMap;
extern const CFStringRef kCGImagePropertyGIFHasGlobalColorMap;
extern const CFStringRef kCGImagePropertyGIFUnclampedDelayTime;

extern const CFStringRef kCGImagePropertyDPIHeight;
extern const CFStringRef kCGImagePropertyDPIWidth;
extern const CFStringRef kCGImagePropertyPixelWidth;
extern const CFStringRef kCGImagePropertyPixelHeight;
extern const CFStringRef kCGImagePropertyDepth;
extern const CFStringRef kCGImagePropertyOrientation;
extern const CFStringRef kCGImagePropertyIsFloat;
extern const CFStringRef kCGImagePropertyIsIndexed;
extern const CFStringRef kCGImagePropertyHasAlpha;
extern const CFStringRef kCGImagePropertyColorModel;
extern const CFStringRef kCGImagePropertyProfileName;

#endif
